# Generated by Django 5.1.7 on 2025-03-15 10:08

import django.db.models.deletion
import makale.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takip_numarasi', models.CharField(default=makale.models.generate_tracking_id, max_length=64, unique=True)),
                ('baslik', models.CharField(max_length=255)),
                ('pdf_dosya', models.FileField(upload_to='makaleler/')),
                ('yazar_email', models.EmailField(max_length=254)),
                ('yuklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('durum', models.CharField(choices=[('Beklemede', 'Beklemede'), ('Değerlendiriliyor', 'Değerlendiriliyor'), ('Tamamlandı', 'Tamamlandı')], default='Beklemede', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='processinghistory',
            name='anonymized_document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.RemoveField(
            model_name='processinghistory',
            name='document',
        ),
        migrations.RemoveField(
            model_name='processinghistory',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('yazar', 'Yazar'), ('editor', 'Editör'), ('hakem', 'Hakem')], default='yazar', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makale.makale')),
            ],
        ),
        migrations.CreateModel(
            name='HakemAtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atama_tarihi', models.DateTimeField(auto_now_add=True)),
                ('degerlendirme_yapildi', models.BooleanField(default=False)),
                ('hakem', models.ForeignKey(limit_choices_to={'role': 'hakem'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makale.makale')),
            ],
        ),
        migrations.CreateModel(
            name='Degerlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum', models.TextField()),
                ('pdf_dosya', models.FileField(blank=True, null=True, upload_to='degerlendirmeler/')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('hakem', models.ForeignKey(limit_choices_to={'role': 'hakem'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makale.makale')),
            ],
        ),
        migrations.CreateModel(
            name='AnonymizedMakale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonim_makale_pdf', models.FileField(upload_to='anonimleştirilmiş_makaleler/')),
                ('islenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('hash_degeri', models.CharField(blank=True, max_length=64, unique=True)),
                ('orijinal_makale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='makale.makale')),
            ],
        ),
        migrations.DeleteModel(
            name='AnonymizedDocument',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='ProcessingHistory',
        ),
    ]
