# Generated by Django 5.1.7 on 2025-03-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0002_makale_remove_processinghistory_anonymized_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IlgiAlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('AI', 'Yapay Zeka ve Makine Öğrenimi'), ('HCI', 'İnsan-Bilgisayar Etkileşimi'), ('BIGDATA', 'Büyük Veri ve Veri Analitiği'), ('SECURITY', 'Siber Güvenlik'), ('NETWORK', 'Ağ ve Dağıtık Sistemler')], max_length=20)),
                ('isim', models.CharField(max_length=100)),
            ],
        ),
    ]
