# Generated by Django 5.1.7 on 2025-03-15 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0003_ilgialani'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='alanlar',
            field=models.ManyToManyField(blank=True, to='makale.ilgialani'),
        ),
        migrations.AddField(
            model_name='makale',
            name='anahtar_kelimeler',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Hakem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilgi_alanlari', models.ManyToManyField(blank=True, to='makale.ilgialani')),
                ('kullanici', models.OneToOneField(limit_choices_to={'role': 'hakem'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='degerlendirme',
            name='hakem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makale.hakem'),
        ),
        migrations.AlterField(
            model_name='hakematama',
            name='hakem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makale.hakem'),
        ),
    ]
