# Generated by Django 5.1.7 on 2025-03-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0004_makale_alanlar_makale_anahtar_kelimeler_hakem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymizedmakale',
            name='anonim_makale_pdf',
            field=models.FileField(upload_to='anonim_makaleler/'),
        ),
    ]
