# Generated by Django 5.1.7 on 2025-03-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0005_alter_anonymizedmakale_anonim_makale_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='anahtar_kelimeler',
            field=models.TextField(blank=True),
        ),
    ]
