# Generated by Django 5.1.7 on 2025-03-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0006_alter_makale_anahtar_kelimeler'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymizedmakale',
            name='sifreli_veriler',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
