# Generated by Django 5.1.7 on 2025-03-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0007_anonymizedmakale_sifreli_veriler'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymizedmakale',
            name='secilen_bilgi_turleri',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
