# Generated by Django 5.1.7 on 2025-03-31 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0008_anonymizedmakale_secilen_bilgi_turleri'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakaleMesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='makale.makale')),
            ],
        ),
    ]
