# Generated by Django 5.1.7 on 2025-03-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0009_makalemesaj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makalemesaj',
            name='gonderen',
            field=models.CharField(choices=[('Yazar', 'Yazar'), ('Editör', 'Editör')], max_length=10),
        ),
    ]
