# Generated by Django 5.1.7 on 2025-04-02 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0010_alter_makalemesaj_gonderen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymizedmakale',
            name='orijinal_makale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anonim_makale', to='makale.makale'),
        ),
    ]
