# Generated by Django 5.1.7 on 2025-04-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0011_alter_anonymizedmakale_orijinal_makale'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='sonuc_pdf',
            field=models.FileField(blank=True, null=True, upload_to='sonuclar/'),
        ),
    ]
